### ISSUE TITLE
Create website maintenance documentation

### ISSUE THREAD

**Issue by jordanhom** [ColectivaLegal/waisn-website#8]
**Problem**
Right now handle only have two Tech Team volunteers heavily involved with the website. Once it is created, we want the ability to hand off to other non-technical individuals for them to update content and do basic maintenance. There's a lot of tribal knowledge floating about.

**Solution**
Create a WAISN Website wiki. Can start with a memdump, and then update it over time to make it user friendly./

**Comment by JPeterCostantini** [comment]
I've posted documentation on administration and maintenance of the web site on the wiki.
